config/routes.rb
Rails.application.routes.draw do
  root 'guests#index'

  devise_for :users, skip: [:sessions]

  resources :guests, only: [:index, :create]

  get '/setup', to: 'setup#index', as: 'setup'
  post '/setup', to: 'setup#perform', as: 'perform_setup'

  resources :machines do
    member do
      post 'start'
      post 'pause'
      post 'resume'
      post 'stop'
      post 'force_stop'
      post 'restart'
      post 'force_restart'

      post 'mount_iso'

      get 'state'
    end

    resources :disks do
      member do
        post 'resize'
        post 'snapshot'
      end
    end
  end

  get '/progress/:id', to: 'progress#progress', as: 'progress'
  get '/machine_progress/:id', to: 'progress#machine', as: 'machine_progress'
end

app/models/infra/machine.rb
require 'active_hash'

class Infra::Machine < Infra::Base
  attr_accessor :id
  attr_accessor :hostname, :uuid, :memory
  attr_accessor :processors, :processor_usage
  attr_accessor :status
  attr_accessor :vnc_password, :vnc_port, :vnc_listen_ip
  attr_accessor :disks
  attr_accessor :networks
  attr_accessor :iso_distro_id, :iso_image_id


  def self.all
    Wvm::Machine.all
  end

  def self.find hostname
    Wvm::Machine.find hostname
  end

  def self.create new_machine
    Wvm::Machine.create new_machine
  end

  def id
    @id ||= MetaMachine.where(hostname: hostname).first.id
  end

  %w(start pause resume stop force_stop restart force_restart).each do |operation|
    define_method operation do
      Wvm::Machine.send operation, hostname
    end
  end

  def create_disk disk
    Wvm::Machine.add_disk disk, self
  end

  def delete_disk disk
    Wvm::Machine.delete_disk disk, self
  end

  def mount_iso iso_image
    Wvm::Machine.mount_iso self, iso_image
  end

  def iso_distro
    Plans::IsoDistro.find @iso_distro_id if @iso_distro_id
  end

  def iso_image
    Plans::IsoImage.find @iso_image_id if @iso_image_id
  end

  def delete
    Wvm::Machine.delete self
  end


  class Status < ActiveHash::Base
    # TODO: https://github.com/pluginaweek/state_machine

    self.data = [
        {id: :running, name: 'Running', running: true, icon: 'fa fa-play'},
        {id: :saved, name: 'Saved', running: false, icon: 'fa fa-stop'},
        {id: :suspended, name: 'Paused', running: false, icon: 'fa fa-pause'},
        {id: :stopped, name: 'Stopped', running: false, icon: 'fa fa-stop'},
        {id: :unknown, name: 'Unknown', running: nil, icon: 'fa fa-question'}
    ]

    def stopped?
      running === false
    end

    def running?
      running
    end

    def to_s
      name
    end
  end
end

app/models/machine.rb
require 'active_hash'

class Machine < Base
  attr_accessor :hostname, :uuid, :memory
  attr_accessor :processors, :processor_usage
  attr_accessor :status
  attr_accessor :vnc_password, :vnc_port
  attr_accessor :disks
  attr_accessor :networks
  attr_accessor :iso_distro_id, :iso_image_id


  def self.all
    Wvm::Machine.all
  end

  def self.find id
    Wvm::Machine.find id
  end

  def id
    hostname
  end

  %w(start pause resume stop force_stop restart force_restart).each do |operation|
    define_method operation do
      Wvm::Machine.send operation, id
    end
  end

  def create_disk disk
    Wvm::Machine.add_disk disk, self
  end

  def delete_disk disk
    Wvm::Machine.delete_disk disk, self
  end

  def mount_iso iso_image
    Wvm::Machine.mount_iso self, iso_image
  end

  def iso_distro
    Plans::IsoDistro.find @iso_distro_id if @iso_distro_id
  end

  def iso_image
    Plans::IsoImage.find @iso_image_id if @iso_image_id
  end

  def delete
    Wvm::Machine.delete self
  end


  class Status < ActiveHash::Base
    # TODO: https://github.com/pluginaweek/state_machine

    self.data = [
        {id: :running, name: 'Running', running: true, icon: 'fa fa-play'},
        {id: :saved, name: 'Saved', running: false, icon: 'fa fa-stop'},
        {id: :suspended, name: 'Suspended', running: false, icon: 'fa fa-pause'},
        {id: :stopped, name: 'Stopped', running: false, icon: 'fa fa-stop'},
        {id: :unknown, name: 'Unknown', running: nil, icon: 'fa fa-question'}
    ]

    def stopped?
      running === false
    end

    def running?
      running
    end

    def to_s
      name
    end
  end
end

app/models/wvm/machine.rb
require 'ipaddress'

class Wvm::Machine < Wvm::Base
  def self.all
    response = call :get, '/1/instances'
    machines = build_all_instances response

    Infra::Elements.new machines
  end

  def self.find id
    response = call :get, "/1/instance/#{id}"

    params = {
      hostname: response[:name],
      uuid: response[:uuid],
      memory: response[:cur_memory],
      processors: response[:vcpu],
      status: determine_status(response),
      vnc_password: response[:vnc_password],
      disks: Wvm::Disk.array_of(response.disks)
    }

    if response.media and not response.media.empty?
      file = response.media.first.image
      iso_image = Plans::IsoImage.by_file(file).first

      if iso_image
        params[:iso_image_id] = iso_image.id
        params[:iso_distro_id] = iso_image.iso_distro.id
      end
    end

    Infra::Machine.new params
  end

  def self.create new_machine
    machine = build_new_machine new_machine

    template = File.dirname(__FILE__) + '/new_machine.xml.slim'
    xml = Slim::Template.new(template, format: :xhtml).render Object.new, {machine: machine}
    call :post, '/1/create', create_xml: '',
        from_xml: xml

    machine = Infra::Machine.find machine.hostname

    machine.create_disk Infra::Disk.new \
        size: new_machine.plan.storage,
        type: new_machine.plan.storage_type

    machine
  end

  OPERATIONS = {
      start: :start,
      pause: :suspend,
      resume: :resume,
      stop: :shutdown,
      force_stop: :destroy,
      restart: :restart
  }

  OPERATIONS.each do |operation_name, libvirt_name|
    define_singleton_method operation_name do |id|
      operation libvirt_name, id
    end
  end

  def self.force_restart id
    operation :destroy, id
    operation :start, id
  end

  def self.add_disk disk, machine
    disk.device = machine.disks.next_device_name
    Wvm::Disk.create disk, machine.uuid

    call :post, "/1/instance/#{machine.hostname}", assign_volume: '',
        file: disk.path, device: disk.device
  end

  def self.delete_disk disk, machine
    call :post, "/1/instance/#{machine.hostname}", unassign_volume: '',
        device: disk.device

    Wvm::Disk.delete disk
  end

  def self.mount_iso machine, iso_image
    call :post, "/1/instance/#{machine.hostname}", mount_iso: '',
        media: iso_image.file # device purposely omitted
  end

  def self.delete machine
    call :post, "/1/instance/#{machine.hostname}", delete: '',
        delete_disk: ''
  end


  private
  def self.sum_up object, &property
    object.map(&property).inject(0, &:+)
  end

  def self.operation operation, id
    call :post, '/1/instances', operation => '', name: id
  end

  def self.determine_status response
    status = case response[:status]
      when 1
        :running
      when 3
        :suspended
      when 5
        response[:has_managed_save_image] == 1 ? :saved : :stopped
      else
        :unknown
    end
    Infra::Machine::Status.find status
  end

  def self.build_all_instances response
    machines = response.instances.map do |machine|
      Infra::Machine.new \
          hostname: machine[:name],
          memory: machine[:memory],
          disks: Wvm::Disk.array_of(machine.storage),
          status: determine_status(machine)
    end
    machines.sort_by &:hostname
  end

  def self.build_new_machine new_machine
    uuid = SecureRandom.uuid
    networks = setup_networks uuid

    Infra::Machine.new \
        uuid: uuid,
        hostname: new_machine.hostname,
        memory: new_machine.plan.memory,
        processors: new_machine.plan.cpu,
        iso_distro_id: new_machine.iso_distro.id,
        iso_image_id: new_machine.iso_distro.iso_images.first.id,
        networks: networks,
        vnc_listen_ip: hypervisor[:vnc_listen_ip],
        vnc_password: SecureRandom.urlsafe_base64(32)
  end

  def self.setup_networks uuid
    networks = Infra::Networks.new
    networks.public = Infra::Network.new \
        pool_name: hypervisor[:network][:id],
        dhcp_network: IPAddress(hypervisor[:network][:address])
    networks
  end
end

app/controllers/machine_controller.rb
class MachineController < ApplicationController
  def index
    @machines = Machine.all.sort_by &:name

    memory = @machines.map(&:memory).inject(0, &:+).megabytes
    storage = @machines.map(&:storage).flatten.map(&:capacity).inject(0, &:+)

    @sum = {
      memory: memory > 0 ? memory : 'N/A',
      storage: storage > 0 ? storage : 'N/A',
    }
  end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :authenticate_user!

  include FindMachine
  find_machine_before_action :id, except: [:index, :new, :create]

  respond_to :html
  respond_to :json, only: [:create, :show]


  def index
    @machines = current_user.machines
    @new_machines = current_user.new_machines
  end

  def new
    @machine ||= NewMachine.new
    @plans ||= Defaults::MachinePlan.all
    @isos ||= Plans::IsoDistro.all
    respond_with @machine
  end

  def create
    machine_params = NewMachine.check_params params
    @machine = current_user.new_machines.build machine_params

    if @machine.save
      MachineCreateJob.perform_later @machine.id
      redirect_to machines_path
      return
    end

    new
  end

  def show
    @disk_types = Infra::DiskType.all
    @disk = Infra::Disk.new
    @iso_images = Plans::IsoImage.all
  end

  def destroy
    MachineDeleteJob.perform_later @meta_machine.id
    redirect_to machines_path
  end

  %w(start pause resume stop force_stop restart force_restart).each do |operation|
    define_method operation do
      render_progress MachineActionJob.perform_later current_user, @meta_machine.id, operation
    end
  end

  def mount_iso
    iso_image_id = params[:machine][:iso_image_id]
    render_progress MachineMountIsoJob.perform_later current_user, @meta_machine.id, iso_image_id
  end

  def state
    render json: @machine.status.attributes
  end
end

app/helpers/machines_helper.rb
module MachinesHelper
  def power_action href, classes = '', is_button = true, &block
    btn_classes = is_button ? 'btn btn-default' : nil
    link_to href, method: :post, class: "action #{classes} #{btn_classes}", &block
  end
end

app/views/machines/index/_console.html.slim
#page-console.text-center
  .console-window-wrapper
    .console-window
      .canvas-wrapper
        canvas data-password=@machine.vnc_password data-uuid=@machine.uuid
      .vm-actions
        .iso
          = form_for @machine, as: :machine, url: mount_iso_machine_path(@machine), method: :post, remote: true do |f|
            = f.collection_select :iso_image_id, @iso_images, :id, :long_name, {prompt: true},
                  class: 'distributions iso_dropdown', id: 'console_machine_iso_image_id'
            i.fa.fa-spinner.fa-spin.hidden
            i.fa.fa-check.hidden
            i.fa.fa-warning.hidden
        .rocket-menu
          = image_tag 'logo/virtkick-logo-pixelart-gray-24.png'
        .restart
          a.btn.btn-default.ctrlaltdel
            | Reboot
          = link_to force_restart_machine_path(@machine), method: :post, remote: true, class: 'btn btn-default hardreset',
              data: {confirm: 'Are you sure? This may cause data loss.', confirm_title: "Hard reset #{@machine.hostname}"}
            | Hard reset
      p.bright-violet.browser-info
        | If the VNC console doesn't appear, please upgrade your browser or try a different one.
      p.bright-violet.status.hidden
        | Machine killed. Now starting it again... &nbsp;
        i.fa.fa-spinner.fa-spin



- content_for :scripts do
  javascript:
    require(['jquery', 'novnc', '!domReady'], function($, RFB) {
      var rfb;
      var hardResetRequested = false;
      var connectLoop = false;
      var $canvasWrapper = $('#page-console').find('.canvas-wrapper');

      function updateConsole() {
        var width, height;
        if (!rfb) {
          width = 640;
          height = 480;
        } else {
          width = rfb.get_display().get_width();
          height = rfb.get_display().get_height();
        }

        // after connecting first noVNC frames are not real screens, so catch only
        // realistic sizes to avoid console flickering
        if (height <= 20) {
          return;
        }

        $canvasWrapper.width(width + "px");
        $canvasWrapper.height(height + "px");

        var margin = 70;
        var left = ($('#page-machine').width() - width - margin) / 2;
        left -= $('.side-menu-wrapper').outerWidth() / 2;

        $('.console-window').css("margin-left", left);
      }

      $('.console').click(function() {
        var connect = function() {
          if (!connectLoop) {
            return;
          }

          var $canvas = $('#page-console').find('canvas');
          var host = window.location.hostname;
          var port = 6080;
          var password = $canvas.attr('data-password');
          var uuid = $canvas.attr('data-uuid');
          document.cookie = 'token=1-' + uuid + '; path=/';
          rfb.connect(host, port, password, '');
        };

        rfb = new RFB({
          'target': $('canvas')[0],
          'repeaterID': '',
          'encrypt': location.protocol === 'https:',
          'true_color': true,
          'local_cursor': true,
          'shared': true,
          'onUpdateState': function(rfb, state, oldstate, statusMsg) {
            if (state === 'normal') {
              $('#page-console .browser-info').hide();
              $('#page-console .status').addClass('hidden');
              hardResetRequested = false;
            } else if (state === 'failed') {
              if (hardResetRequested) {
                $('#page-console .browser-info').hide();
                $('#page-console .status').removeClass('hidden');
              } else {
                $('#page-console .browser-info').show();
                $('#page-console .status').addClass('hidden');
              }
              setTimeout(connect, 1000);
            }
            return;
          },
          'onFBUComplete': function (rfb, fbu) {
            updateConsole();
          },
          'view_only': false,
          'onPasswordRequired': function() {
            console.log('VNC: Password required');
          }
        });

        $('.side-menu-wrapper').addClass('collapsed');

        connectLoop = true;
        connect();
      });

      $('#page-console .ctrlaltdel').click(function() {
        rfb.sendCtrlAltDel();
      });

      $('#page-console .hardreset').click(function() {
        hardResetRequested = true;
      });

      $('.nav a:not(.console)').click(function() {
        if (rfb) {
          rfb.disconnect();
        }
        connectLoop = false;
      });

      $('#page-machine .nav li').click(function (e) {
        if ($(e.currentTarget).find('.console').length == 0) {
          $('.side-menu-wrapper').removeClass('collapsed');
          $('.side-menu').removeClass('expanded');
        }
      });

      $('.side-menu-wrapper .dropdown').click(function () {
        $('.side-menu').toggleClass('expanded');
      });

      $(window).resize(function () {
        updateConsole();
      });

      updateConsole();
    });

app/views/machines/index/_power.html.slim
#page-power
  .row.stats
    .col-sm-3
      .key Memory:
      .val.bigger = number_to_human_size(@machine.memory.megabytes)
    .col-sm-3
      .key Processors:
      - if @machine.status.stopped?
        .val.bigger
          = @machine.processors
          |  CPU
      - else
        .val
          = @machine.processors
          |  CPU
        .progress
          .progress-bar role='progressbar' style="width: #{@machine.processor_usage}%; min-width: 1%"
            span.sr-only
              = @machine.processor_usage
              | % usage
    .col-sm-3
      .key Storage:
      .val = number_to_human_size(@machine.disks.size)
      .progress
        .progress-bar role='progressbar' style="width: #{@machine.disks.usage}%; min-width: 1%"
          span.sr-only
            = number_to_human_size @machine.disks.used
            |  used (
            = @machine.disks.usage
            | %)
    .col-sm-3
      .key State:
      .val.power-state.bigger data-running="#{@machine.status.running?}"
        span
          i class="icon #{@machine.status.icon}"
          span.status = @machine.status.name

  = render partial: '/flash', locals: {section: 'power'}

  .controls
    .btn-group
      = power_action start_machine_path(@machine), 'start' do
        i.icon.fa.fa-play
        span.status Start
      = power_action pause_machine_path(@machine), 'pause only-on' do
        i.icon.fa.fa-pause
        span.status Pause
      = power_action resume_machine_path(@machine), 'resume only-on' do
        i.icon.fa.fa-forward
        span.status Resume
      = power_action stop_machine_path(@machine), 'stop only-on' do
        i.icon.fa.fa-stop
        span.status Stop
      .btn-group
        button.only-on.btn.btn-default.dropdown-toggle type='button' data-toggle='dropdown'
          i.fa.fa-caret-down
        ul.dropdown-menu
          li
            = power_action force_stop_machine_path(@machine), 'force-stop only-on', false do
              span.fa.fa-power-off
              span.status Hard stop
      = power_action restart_machine_path(@machine), 'restart only-on' do
        i.icon.fa.fa-repeat
        span.status Restart
      .btn-group
        button.only-on.btn.btn-default.dropdown-toggle type='button' data-toggle='dropdown'
          i.fa.fa-caret-down
        ul.dropdown-menu
          li
            = power_action force_restart_machine_path(@machine), 'force-restart only-on', false do
              span.icon.fa.fa-power-off
              span.status Hard reset

app/views/machines/index/_scheduler.html.slim
#page-scheduler.text-center
  p Schedule machine lifecycle events like start, stop or restart with a cron-like syntax.

  .create
    a.btn.btn-default.btn-block
      | Create a new event

  table.table.table-striped.text-left
    thead
      tr
        th.action Action
        th.cron Cron rule
        th.next Next on
        th.then Then on
        th.actions
    tbody
      - for schedule in [['play', 'start', '0 12 * * *', '2014-06-28 12:00', '2014-06-29 12:00'],
          ['stop', 'stop', '30 12 * * *', '2014-06-28 12:30', '2014-06-29 12:30']]
        tr
          td.action
            i class="fa fa-#{schedule[0]}" &nbsp;
            = schedule[1]
          td.cron = schedule[2]
          td.next = schedule[3]
          td.then = schedule[4]
          td.actions
            a.btn.btn-default Edit
            a.btn.btn-danger Delete
      tr.new
        td.action
          select.fa.form-control
            option &#xf04b; start
            option &#xf04d; stop
            option &#xf01e; restart
            option &#xf04c; pause
        td.cron
          select.combobox
            option
            option every day at midnight
            option every week on Sunday midnight
            option on the 1st day of month
            option on the last day of month
        td.next
        td.then
        td.actions
          a.btn.btn-default Save


- content_for :scripts do
  javascript:
    $(function() {
      $('tr.new').hide();
      //$('#page-scheduler .combobox').combobox();

      $('#page-scheduler .create').click(function() {
        $('.new').show();
        $('.combobox').focus();

        $('.combobox').keydown(function() {
          $('.new .next').text('2014-07-03 13:37');
          $('.new .then').text('2014-07-08 13:37');
        })
      });
    });

app/views/machines/index/_settings.html.slim
#page-settings
  h3 CD image

  = form_for @machine, as: :machine, url: mount_iso_machine_path(@machine), method: :post, remote: true do |f|
    label
      | Mount ISO: &nbsp;
      = f.collection_select :iso_image_id, @iso_images, :id, :long_name, {prompt: true}, class: 'iso_dropdown'
      i.fa.fa-spinner.fa-spin.hidden
      i.fa.fa-check.hidden
      i.fa.fa-warning.hidden

  h3 Danger Zone

  p
    = link_to 'Delete machine', machine_path(@machine), method: 'delete', class: 'btn btn-danger',
          data: {confirm: 'Are you sure? This cannot be undone.', confirm_title: "Delete #{@machine.hostname}"}

app/views/machines/index/_stats.html.slim
#page-stats.text-center

app/views/machines/index/_storage.html.slim
#page-storage.text-center

  = render partial: '/flash', locals: {section: 'storage'}

  = form_for @disk, remote: true, url: machine_disks_path(@machine) do |f|
    .create.text-right
      a.btn.btn-primary.create-button
        | Create a new disk
      div.new
        div.name
          = @machine.disks.next_device_name
        div.type
          = collection_select :disk, :type, @disk_types, :id, :name, {}, class: 'type form-control'
        div.size
          = collection_select :disk, :size_plan, Defaults::DiskSizePlan.all, :id, :name, {}, class: 'size form-control'
          | GB
        = f.submit 'Create', class: 'btn btn-primary save-button'

  /TODO: snapshot all images (the only revertable way for snapshots in libvirt)

  table.table.table-striped.text-left
    thead
      tr
        th.name Disk name
        th.actions
        th.type Type
        th.size Size
    tbody
      - @machine.disks.each do |disk|
        / TODO: Handle case when disk was detached and deleted, but virtio wasn't present in VM (e.g. boot loader screen).
        / Such a disk should be grayed out. The tooltip should say "This disk will disappear after you stop your VM".
        tr
          td.name
            = disk.device
            i.fa.fa-spinner.fa-spin.hidden
            i.fa.fa-check.hidden
            i.fa.error.fa-warning.hidden
            span.error.message
          td.actions
            div.buttons
              / TODO: resize. (virStorageVol.resize)
              = link_to machine_disk_path(@machine, disk), method: 'delete', remote: true, class: 'btn delete-disk',
                    data: {confirm: 'Are you sure? This cannot be undone.', confirm_title: "Delete #{disk.device}"} do
                span.oi.oi-delete
                span.action Delete
          td.type = disk.type
          td.size = number_to_human_size disk.size
      tr.example.hidden
        td.name
          span.name
          i.fa.fa-spinner.fa-spin
          i.fa.fa-check.hidden
          i.fa.error.fa-warning.hidden
          span.error.message
        td.actions
          div.buttons
        td.type
        td.size