config/routes.rb
Rails.application.routes.draw do
  root 'guests#index'

  devise_for :users, skip: [:sessions]

  resources :guests, only: [:index, :create]

  get '/setup', to: 'setup#index', as: 'setup'
  post '/setup', to: 'setup#perform', as: 'perform_setup'

  resources :machines do
    member do
      post 'start'
      post 'pause'
      post 'resume'
      post 'stop'
      post 'force_stop'
      post 'restart'
      post 'force_restart'

      post 'mount_iso'

      get 'state'
    end

    resources :disks do
      member do
        post 'resize'
        post 'snapshot'
      end
    end
  end

  get '/progress/:id', to: 'progress#progress', as: 'progress'
  get '/machine_progress/:id', to: 'progress#machine', as: 'machine_progress'
end

app/models/infra/machine.rb
require 'active_hash'

class Infra::Machine < Infra::Base
  attr_accessor :id
  attr_accessor :hostname, :uuid, :memory
  attr_accessor :processors, :processor_usage
  attr_accessor :status
  attr_accessor :vnc_password, :vnc_port, :vnc_listen_ip
  attr_accessor :disks
  attr_accessor :networks
  attr_accessor :iso_distro_id, :iso_image_id


  def self.all
    Wvm::Machine.all
  end

  def self.find hostname
    Wvm::Machine.find hostname
  end

  def self.create new_machine
    Wvm::Machine.create new_machine
  end

  def id
    @id ||= MetaMachine.where(hostname: hostname).first.id
  end

  %w(start pause resume stop force_stop restart force_restart).each do |operation|
    define_method operation do
      Wvm::Machine.send operation, hostname
    end
  end

  def create_disk disk
    Wvm::Machine.add_disk disk, self
  end

  def delete_disk disk
    Wvm::Machine.delete_disk disk, self
  end

  def mount_iso iso_image
    Wvm::Machine.mount_iso self, iso_image
  end

  def iso_distro
    Plans::IsoDistro.find @iso_distro_id if @iso_distro_id
  end

  def iso_image
    Plans::IsoImage.find @iso_image_id if @iso_image_id
  end

  def delete
    Wvm::Machine.delete self
  end


  class Status < ActiveHash::Base
    # TODO: https://github.com/pluginaweek/state_machine

    self.data = [
        {id: :running, name: 'Running', running: true, icon: 'fa fa-play'},
        {id: :saved, name: 'Saved', running: false, icon: 'fa fa-stop'},
        {id: :suspended, name: 'Paused', running: false, icon: 'fa fa-pause'},
        {id: :stopped, name: 'Stopped', running: false, icon: 'fa fa-stop'},
        {id: :unknown, name: 'Unknown', running: nil, icon: 'fa fa-question'}
    ]

    def stopped?
      running === false
    end

    def running?
      running
    end

    def to_s
      name
    end
  end
end

app/models/machine.rb
require 'active_hash'

class Machine < Base
  attr_accessor :hostname, :uuid, :memory
  attr_accessor :processors, :processor_usage
  attr_accessor :status
  attr_accessor :vnc_password, :vnc_port
  attr_accessor :disks
  attr_accessor :networks
  attr_accessor :iso_distro_id, :iso_image_id


  def self.all
    Wvm::Machine.all
  end

  def self.find id
    Wvm::Machine.find id
  end

  def id
    hostname
  end

  %w(start pause resume stop force_stop restart force_restart).each do |operation|
    define_method operation do
      Wvm::Machine.send operation, id
    end
  end

  def create_disk disk
    Wvm::Machine.add_disk disk, self
  end

  def delete_disk disk
    Wvm::Machine.delete_disk disk, self
  end

  def mount_iso iso_image
    Wvm::Machine.mount_iso self, iso_image
  end

  def iso_distro
    Plans::IsoDistro.find @iso_distro_id if @iso_distro_id
  end

  def iso_image
    Plans::IsoImage.find @iso_image_id if @iso_image_id
  end

  def delete
    Wvm::Machine.delete self
  end


  class Status < ActiveHash::Base
    # TODO: https://github.com/pluginaweek/state_machine

    self.data = [
        {id: :running, name: 'Running', running: true, icon: 'fa fa-play'},
        {id: :saved, name: 'Saved', running: false, icon: 'fa fa-stop'},
        {id: :suspended, name: 'Suspended', running: false, icon: 'fa fa-pause'},
        {id: :stopped, name: 'Stopped', running: false, icon: 'fa fa-stop'},
        {id: :unknown, name: 'Unknown', running: nil, icon: 'fa fa-question'}
    ]

    def stopped?
      running === false
    end

    def running?
      running
    end

    def to_s
      name
    end
  end
end

app/models/wvm/machine.rb
require 'ipaddress'

class Wvm::Machine < Wvm::Base
  def self.all
    response = call :get, '/1/instances'
    machines = build_all_instances response

    Infra::Elements.new machines
  end

  def self.find id
    response = call :get, "/1/instance/#{id}"

    params = {
      hostname: response[:name],
      uuid: response[:uuid],
      memory: response[:cur_memory],
      processors: response[:vcpu],
      status: determine_status(response),
      vnc_password: response[:vnc_password],
      disks: Wvm::Disk.array_of(response.disks)
    }

    if response.media and not response.media.empty?
      file = response.media.first.image
      iso_image = Plans::IsoImage.by_file(file).first

      if iso_image
        params[:iso_image_id] = iso_image.id
        params[:iso_distro_id] = iso_image.iso_distro.id
      end
    end

    Infra::Machine.new params
  end

  def self.create new_machine
    machine = build_new_machine new_machine

    template = File.dirname(__FILE__) + '/new_machine.xml.slim'
    xml = Slim::Template.new(template, format: :xhtml).render Object.new, {machine: machine}
    call :post, '/1/create', create_xml: '',
        from_xml: xml

    machine = Infra::Machine.find machine.hostname

    machine.create_disk Infra::Disk.new \
        size: new_machine.plan.storage,
        type: new_machine.plan.storage_type

    machine
  end

  OPERATIONS = {
      start: :start,
      pause: :suspend,
      resume: :resume,
      stop: :shutdown,
      force_stop: :destroy,
      restart: :restart
  }

  OPERATIONS.each do |operation_name, libvirt_name|
    define_singleton_method operation_name do |id|
      operation libvirt_name, id
    end
  end

  def self.force_restart id
    operation :destroy, id
    operation :start, id
  end

  def self.add_disk disk, machine
    disk.device = machine.disks.next_device_name
    Wvm::Disk.create disk, machine.uuid

    call :post, "/1/instance/#{machine.hostname}", assign_volume: '',
        file: disk.path, device: disk.device
  end

  def self.delete_disk disk, machine
    call :post, "/1/instance/#{machine.hostname}", unassign_volume: '',
        device: disk.device

    Wvm::Disk.delete disk
  end

  def self.mount_iso machine, iso_image
    call :post, "/1/instance/#{machine.hostname}", mount_iso: '',
        media: iso_image.file # device purposely omitted
  end

  def self.delete machine
    call :post, "/1/instance/#{machine.hostname}", delete: '',
        delete_disk: ''
  end


  private
  def self.sum_up object, &property
    object.map(&property).inject(0, &:+)
  end

  def self.operation operation, id
    call :post, '/1/instances', operation => '', name: id
  end

  def self.determine_status response
    status = case response[:status]
      when 1
        :running
      when 3
        :suspended
      when 5
        response[:has_managed_save_image] == 1 ? :saved : :stopped
      else
        :unknown
    end
    Infra::Machine::Status.find status
  end

  def self.build_all_instances response
    machines = response.instances.map do |machine|
      Infra::Machine.new \
          hostname: machine[:name],
          memory: machine[:memory],
          disks: Wvm::Disk.array_of(machine.storage),
          status: determine_status(machine)
    end
    machines.sort_by &:hostname
  end

  def self.build_new_machine new_machine
    uuid = SecureRandom.uuid
    networks = setup_networks uuid

    Infra::Machine.new \
        uuid: uuid,
        hostname: new_machine.hostname,
        memory: new_machine.plan.memory,
        processors: new_machine.plan.cpu,
        iso_distro_id: new_machine.iso_distro.id,
        iso_image_id: new_machine.iso_distro.iso_images.first.id,
        networks: networks,
        vnc_listen_ip: hypervisor[:vnc_listen_ip],
        vnc_password: SecureRandom.urlsafe_base64(32)
  end

  def self.setup_networks uuid
    networks = Infra::Networks.new
    networks.public = Infra::Network.new \
        pool_name: hypervisor[:network][:id],
        dhcp_network: IPAddress(hypervisor[:network][:address])
    networks
  end
end

app/controllers/machine_controller.rb
class MachineController < ApplicationController
  def index
    @machines = Machine.all.sort_by &:name

    memory = @machines.map(&:memory).inject(0, &:+).megabytes
    storage = @machines.map(&:storage).flatten.map(&:capacity).inject(0, &:+)

    @sum = {
      memory: memory > 0 ? memory : 'N/A',
      storage: storage > 0 ? storage : 'N/A',
    }
  end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :authenticate_user!

  include FindMachine
  find_machine_before_action :id, except: [:index, :new, :create]

  respond_to :html
  respond_to :json, only: [:create, :show]


  def index
    @machines = current_user.machines
    @new_machines = current_user.new_machines
  end

  def new
    @machine ||= NewMachine.new
    @plans ||= Defaults::MachinePlan.all
    @isos ||= Plans::IsoDistro.all
    respond_with @machine
  end

  def create
    machine_params = NewMachine.check_params params
    @machine = current_user.new_machines.build machine_params

    if @machine.save
      MachineCreateJob.perform_later @machine.id
      redirect_to machines_path
      return
    end

    new
  end

  def show
    @disk_types = Infra::DiskType.all
    @disk = Infra::Disk.new
    @iso_images = Plans::IsoImage.all
  end

  def destroy
    MachineDeleteJob.perform_later @meta_machine.id
    redirect_to machines_path
  end

  %w(start pause resume stop force_stop restart force_restart).each do |operation|
    define_method operation do
      render_progress MachineActionJob.perform_later current_user, @meta_machine.id, operation
    end
  end

  def mount_iso
    iso_image_id = params[:machine][:iso_image_id]
    render_progress MachineMountIsoJob.perform_later current_user, @meta_machine.id, iso_image_id
  end

  def state
    render json: @machine.status.attributes
  end
end

app/helpers/machines_helper.rb
module MachinesHelper
  def power_action href, classes = '', is_button = true, &block
    btn_classes = is_button ? 'btn btn-default' : nil
    link_to href, method: :post, class: "action #{classes} #{btn_classes}", &block
  end
end

app/views/machines/index.html.slim
- @header = 'Machines'
- @icon = 'monitor'

- content_for :action do
  - if user_signed_in?
    = link_to 'Create a new machine', new_machine_path, class: 'btn btn-primary btn-block'

#page-index
  .items
    ul
      li
        p
          i.oi.oi-monitor
          | Machines
        p.value = @machines.count
      li
        p
          i.oi.oi-puzzle-piece
          | Memory
        p.value = number_to_human_size_with_unit @machines.sum(&:memory).megabytes, min_unit: 'MB'
      li
        p
          i.fa.fa-database
          | Storage
        p.value = number_to_human_size_with_unit @machines.deep_sum(:disks, :size), min_unit: 'GB'
      li
        p
          i.oi.oi-credit-card
          | Monthly
        p.value free

  - if @machines.count + @new_machines.count > 0
    table.table.table-striped
      thead
        tr
          th.name Name
          th.memory Memory
          th.storage Storage
      tbody
        - @new_machines.each do |new_machine|
          - next if new_machine.finished? and new_machine.error_message.nil?
          tr
            - if new_machine.error_message
              - style = {class: 'failed', icon: 'fa-warning'}
            - else
              - style = {class: 'creating', icon: 'fa-spinner fa-spin'}

            td.name class=style[:class] data-url=machine_progress_path(new_machine)
              i class="fa #{style[:icon]}"
              = new_machine.hostname
              span.error = new_machine.error_message
            td.memory  = number_to_human_size(new_machine.plan.memory.gigabytes)
            td.storage = number_to_human_size(new_machine.plan.storage)
        - @machines.each do |machine|
          tr
            td.name class=(machine.status.running? ? 'on' : 'off')
              i class=machine.status.icon
              a href=machine_path(machine) = machine.hostname
            td.memory = number_to_human_size(machine.memory.megabytes)
            td.storage = number_to_human_size(machine.disks.sum &:size)
  - else
    p You don't have a machine yet. Kick things off and #{link_to 'create one!', new_machine_path}

- content_for :scripts do
  javascript:
    require(['jquery', '!domReady'], function($) {
      var $creating = $('.creating');
      if ($creating.length > 0) {
        var url = $creating.attr('data-url');
        setInterval(function() {
          $.ajax(url).success(function(data) {
            if (!data.finished) {
              return;
            }

            if (data.error_message) {
              window.location.reload(false);
            } else {
              window.location.pathname = '/machines/' + data.given_meta_machine_id;
            }
          });
        }, 500);
      }
    });

app/views/machines/new.html.slim
- @header = 'Create a New Machine'
- @icon = 'monitor'

#page-new-machine
  = form_for @machine, as: :machine, url: machines_path(@machine), method: :post do |f|
    = render partial: '/flash', locals: {section: 'new_machine'}

    .form-group.details
      - attrs = {placeholder: 'Machine Hostname', class: 'form-control'}
      - attrs[:autofocus] = true if @machine.hostname.nil? or errors_for?(@machine, :hostname)
      = f.text_field :hostname, attrs
      = errors_for @machine, :hostname

    .form-group
      h2
        i.oi.oi-cart
        | Choose a plan
      .form-group.text-center
        .plans.btn-group data-toggle='buttons'
          - for plan in @plans
            - active = @machine.plan == plan ? 'active' : ''
            = f.label :plan_id, class: "btn btn-info plan #{active} fixed-width" do
              = f.radio_button :plan_id, plan.id
              span.title
                = number_to_human_size(plan.memory.gigabytes)
                |  RAM
              br
              span.val
                = number_to_human_size(plan.storage)
                |  SSD
              br
              span.val
                = plan.cpu
                |  CPU

    .form-group.image
      h2
        i.oi.oi-aperture
        | Pick an image
      .form-group.text-center
        .image-types.btn-group data-toggle='buttons'
          - for type in [['Mount ISO', 'isos'], ['Appliance', 'appliances'], ['1-Click App', 'apps']]
            - name = type[0]
            - id = type[1]
            - active = @machine.image_type == id ? 'active' : ''
            = f.label :image_type, class: "btn btn-info image-type #{active}" do
              = f.radio_button :image_type, id, class: id
              span.title = name

        .image-type-group.appliances.btn-group data-toggle="buttons"
          p VirtKick will deliver appliances with various Linux distributions. Coming soon!

        - active = @machine.iso_distro ? 'active' : ''
        div class="image-type-group isos btn-group #{active}" data-toggle="buttons"
          - for iso in @isos
            - active = @machine.iso_distro == iso ? 'active' : ''
            = f.label :iso_distro_id, class: "btn btn-info distro #{active}" do
              - image = 'distros/' + iso.code + '.png'
              .wrap
                = image_tag image, alt: iso.name
              = f.radio_button :iso_distro_id, iso.id
              span.name = iso.name

        .image-type-group.apps.btn-group data-toggle="buttons"
          p VirtKick will deliver a 1-click integration with Sandstorm.
          p It allows you to install many webapps with a single click. Coming soon!

        .form-group.text-center
          = f.submit 'Create a Machine', class: 'create btn btn-primary btn-lg'


- content_for :scripts do
    javascript:
      require(['jquery', '!domReady'], function($) {
        $('.image-type-group:not(.active)').hide();

        $('.image-type').click(function() {
          $('.image-type-group').hide();
          var selected = $(this).find('input').attr('class');
          $('.image-type-group.' + selected).show();

          $('.create.btn').attr('disabled', selected !== 'isos');
        });

        $('.create').closest('form').submit(function () {
          $('.create').val('Loading...').attr('disabled', 'disabled');
        });
      });

app/views/machines/show.html.slim
- content_for :header do
  h1
    i.oi.oi-monitor
    = @machine.hostname


#page-machine
  - tabs = %w(power console storage settings)
  ul.nav.nav-pills.nav-justified
    - for tab in tabs
      li class="#{'active' if tab == 'power'}"
        a data-toggle='tab' href="##{tab}" class=tab = tab.capitalize

  .tab-content
    - for page in tabs
      .tab-pane id=page class="#{'active' if page == 'power'}"
        = render partial: "machines/index/#{page}"

- content_for :scripts do
  javascript:
    require(['jquery', 'pages/machine'], function($) {
      $(function() {
        var hash = window.location.hash.substring(1);
        if (hash.length > 0) {
          $('a.' + hash).click();
        }

        $('.nav-pills a').click(function() {
          window.location.hash = $(this).attr('class');
        });
      });
    });